services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true  # Allows anonymous access (optional)
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true  # Enable embedding

